name: CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Tools
        uses: liblaf/repo/.github/actions/install@main
        with:
          brew: coreutils gnu-tar make wget
          choco: gnuwin32-coreutils.install make wget
      - name: Build
        run: make dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist/*
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: version
        name: Get Version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: v${{ steps.version.outputs.version }}
          files: "artifacts/*"
          recreate: true
