name: CI

on:
  push:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - name: Install GNU Softwares
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils gnu-tar make wget
          choco: gnuwin32-coreutils.install make wget
      - name: Build
        run: task dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist/*
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

  release:
    name: Release
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: version
        name: Read Version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Delete Existing Release
        run: gh release --repo="${{ github.repository }}" delete "v${{ steps.version.outputs.version }}" --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Create GitHub Release
        run: gh release --repo="${{ github.repository }}" create "v${{ steps.version.outputs.version }}" artifacts/**/* --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

  check:
    name: Check
    needs:
      - build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
